### ISSUE TITLE
Enquiry about the step of the scanning

### ISSUE THREAD

**Issue by mickey2012ex** [insideapp-oss/sonar-apple#64]
Can i scan the project without xcodebuild if i don't need the test coverage?
Is it appropriate to only install SwiftLint and OCLint then run the sonar-scanner?

**Comment by gaelfoppolo** [comment]
Hello @mickey2012ex,
You can perfectly skip the test coverage if don't need it.
SwiftLint runs on its own, so need to perform an `xcodebuild` before.
However, the OCLint analysis uses a JSON Compilation Database that needs to be generated before.
You can either use `xcodebuild` (see `-gen-cdb-fragment-path` flag in the `xcodebuild` example command) or `xcpretty`.
Previously the plugin was using `xcpretty` but we moved to use `xcodebuild`, to remove a dependency and keep the number of external command to run as minimal as possible.

**Comment by mickey2012ex** [comment]
@gaelfoppolo Thanks for your help. I can scan it with xcpretty

However, there is an error when using xcodebuild
clang: error: unknown argument: '-gen-cdb-fragment-path'
clang: error: cannot specify -o when generating multiple output files

**Comment by gaelfoppolo** [comment]
Can you share the full `xcodebuild` command you are trying to? We can't help you without these kind of informaton.

**Comment by mickey2012ex** [comment]
Thank you for your great help. The full xcodebuild command as follows: 

xcrun xcodebuild clean build \ 
-project MyApp.xcodeproj \
-scheme 'MyApp' \ 
-sdk iphonesimulator \
-destination 'generic/platform=iOS Simulator' \
-derivedDataPath ./derivedData \ 
-resultBundlePath build/result.xcresult \
OTHER_CFLAGS="\$(inherited) -gen-cdb-fragment-path build/compilation_database"

**Comment by gaelfoppolo** [comment]
Your command is malformed. You are missing a few backslashes at the end of the lines. Also you forgot a backslash before the dollar sign in `OTHER_CFLAGS`. Here your fixed command.

```
xcrun xcodebuild clean build \
  -project MyApp.xcodeproj \
  -scheme 'MyApp' \
  -sdk iphonesimulator \
  -destination 'generic/platform=iOS Simulator' \
  -derivedDataPath ./derivedData \
  -resultBundlePath build/result.xcresult \
  OTHER_CFLAGS="\$(inherited) -gen-cdb-fragment-path build/compilation_database"
```

**Comment by mickey2012ex** [comment]
> Your command is malformed. You are missing a few backslashes at the end of the lines. Also you forgot a backslash before the dollar sign in `OTHER_CFLAGS`. Here your fixed command.
> 
> ```
> xcrun xcodebuild clean build \
>   -project MyApp.xcodeproj \
>   -scheme 'MyApp' \
>   -sdk iphonesimulator \
>   -destination 'generic/platform=iOS Simulator' \
>   -derivedDataPath ./derivedData \
>   -resultBundlePath build/result.xcresult \
>   OTHER_CFLAGS="\$(inherited) -gen-cdb-fragment-path build/compilation_database"
> ```

Sorry for my typo mistake. My xcodebuild command is same as your command provided.
I also copied your suggested command, but received same error.

xcodebuild version is 11.2.1, Build version11B500
My working command via xcpretty
xcrun xcodebuild clean build \
  -project MyApp.xcodeproj \ 
  -scheme 'MyApp' \
  -sdk iphonesimulator \
  -destination 'generic/platform=iOS Simulator' \
  -derivedDataPath ./derivedData \
  -resultBundlePath build/result.xcresult \
  | xcpretty -r json-compilation-database -o build/compilation_database/compile_commands.json

**Comment by gaelfoppolo** [comment]
I think you might be using an Xcode version that is too old, and doesn't support the `-gen-cdb-fragment-path` flag.
I would recommand to upgrade to the latest Xcode version.
