### ISSUE TITLE
No code errors were analyzed

### ISSUE THREAD

**Issue by FirstDKS521** [insideapp-oss/sonar-apple#79]
Mac OS 14.0

The latest version of sonar-apple plug-in, the installation location is no problem

Latest version of SonarQube

In the root directory of the project, execute the sonar-scanner command. 
After success, no code smell related to OC and Swift can be seen on the SonarQube platform. 
Only js, HTML, and css languages are detected. Why?

**Comment by gaelfoppolo** [comment]
Hi @FirstDKS521,
Can you share your `sonar-project.properties`?
Did you run any `xcodebuild` command before `sonar-scanner` like explained in the README?

**Comment by FirstDKS521** [comment]
> Hi @FirstDKS521, Can you share your `sonar-project.properties`? Did you run any `xcodebuild` command before `sonar-scanner` like explained in the README?

sonar-project.properties:
sonar.token=xxx
sonar.host.url=http://localhost:9000
sonar.projectKey=aaa
sonar.projectName=aaa
sonar.apple.workspace=aaa.xcworkspace
sonar.apple.project=aaa.xcodeproj
sonar.sourceEncoding=UTF-8

I did not execute the xcodebuild command before executing sonar-scanner;
Because even if the xcodebuild command is executed, the generated compile_commands.json file is larger than 20M and cannot be uploaded;
Let's look at the sonar documentation. The sonar-scanner command can directly scan the source code and does not rely on the compile_commands.json file, right?
Thanks~

**Comment by gaelfoppolo** [comment]
Well first, your `sonar-project.properties` is missing `sonar.sources` or `sonar.tests` so you might want to check that first. See the example one in the README.

Sonar is indexing the code source yes, but it does nothing else. It's the plugin that does the scanning, gather the results and then upload them to SonarQube, at the end of the analysis.

As explained at the top of the README, each feature provided by the plugin require a tool.
You don't have to run xcodebuild, but you will miss the majority of information that this plugin provide.

Please:
- configure your `sonar-project.properties` properly
- install the tools listed in the README (in you want the feature associated)
- run `xcodebuild` command (eee the example one in the README and tune it for your project)

You can launch `sonar-scanner -X` to get debug log and get a better understanding of your issues.

**Comment by pravindodia** [comment]
+1
