### ISSUE TITLE
Question about running the scanner on a CI environment

### ISSUE THREAD

**Issue by ahmadalfy** [insideapp-oss/sonar-apple#93]
I am using Gitlab CI and there are no Macs involved. Is it possible that the scanner scan my project and send the results directly to my self-hosted SonarQube? Because every tutorial that I see is for people running this setup on their local machines.

Appreciate your feedback and sorry for adding this as an issue. The project doesn't have the discussions enabled.

**Comment by zippy1978** [comment]
Hi @ahmadalfy !

I think it is possible to add or pay to have Mac on Gitlab CI.

However if you can't use a Mac, you can still run the analysis from a Linux machine where you can install SwiftLint and mobsfscan: you won't get dead code, tests results and tests coverage, but it is maybe enough for you ?

**Comment by ahmadalfy** [comment]
Thank you for the clarification. I ran it on a Docker image and it produced the results. It was sufficient at this time and thankfuly we are migrating to one of the service providers specialized in mobile devops.

Thanks again

**Comment by sherifkayad** [comment]
@ahmadalfy can you please share your docker image? I am having the same exact problem like you are and I need to run the scans from a Linux machine. The coverage report I was able to get using Slather and Fastlane in the Cobertura XML format
